export const SET_IS_LOADING = 'SET_IS_LOADING';
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_ERROR = 'FETCH_SEARCH_RESULTS_ERROR';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SORT_MOVIES = 'SORT_MOVIES';
